### ISSUE TITLE
Add users with Devise 

### ISSUE THREAD

**Issue by DC7806** [DC7806/goodbite#5]
- [x] Define features for user authentication

**Comment by RocketSH** [comment]
user驗證主相關功能

- [ ] 註冊/Login logout  (ticket x1)
- [ ] 第三方登入 (ticket x1)
- [ ] 邀請協作者by email (ticket x1)
        - 協作者開放create newsletter & email view, create, edit
        - 協作者不開放發信功能

**Comment by koten0224** [comment]
把gem裝起來
user model生起來
＃ 孤狗？fb？欄位（maybe later)
view g起來 （擺著不做事也好）

2.
login后路徑導向
